// GITHUB BASE API URL
export const BASE_API_URL = 'https://api.github.com/graphql';

// THIS IS GITHUB TOKEN WITH BASIC PERMISSIONS FROM DUMMY GITHUB ACCOUNT
// FOR SIMPLICITY REASONS IT IS USED IN THIS WAY
// ONE OF THE SOLUTIONS TO BYPASS THIS WOULD BE SETTING UP SERVER SIDE API CALLS WITH ENVIRONMENT VARIABLES
export const TOKEN = '1bf346bf494480f892a56bd0c501daa78d0611f5';

